name:                WDTFoxSay
version:             0.1.0.0
github:              "jonator/WDTFoxSay"
license:             BSD3
author:              "Jonathan Ator"
maintainer:          "jonathanator0@gmail.com"
copyright:           "2018 Jonathan Ator"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jonator/WDTFoxSay#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  WDTFoxSay-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WDTFoxSay

tests:
  WDTFoxSay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WDTFoxSay
